import argparse
import pathlib
import pandas as pd

# Use CAT input table and pydamage results to summarise damage patterns per taxon or sample

def filter_tax_ranks(df, tax_ranks):
    # Remove rows where all selected ranks have no support
    df_filt = df[df["classification"] == "taxid assigned"]
    mask = df_filt[tax_ranks].apply(lambda row: any(val != "no support" for val in row), axis = 1)
    df_filt = df_filt[mask]
    return(df_filt)

def parse_damage_files(path):
    # Load all read depth files and combine into one
    print("Loading damage files in " + str(path))
    damage_files = list(path.glob(f"*/pydamage_results/pydamage_results.csv"))
    print(str(len(damage_files)) + " files found. Combining tables...")
    dfs = []
    i = 0
    for file in damage_files:
        i += 1
        # Extract sample name
        sample = str(file).replace(str(path) + "/MEGAHIT-", "").replace("/pydamage_results/pydamage_results.csv", "")
        if i % 10 == 0:
            print(str(i) + ": Parsing " + sample)
        df = pd.read_csv(file, sep = ",")
        # Keep relevant columns and add sample name to contigName to distinguish samples when combining
        df = df[["reference", "damage_model_pmax"]]
        df.columns = ["contigName", "damage_model_pmax"]
        df["contigName"] = sample + "_" + df.contigName
        dfs.append(df)
    combined = pd.concat(dfs, ignore_index=True)
    print("The combined table contains " + str(combined.shape[0]) + " contigs\n")
    return(combined)

def parse_cat_files(path, tax_ranks):
    # Load all read CAT files and combine into one
    print("Loading contig taxonomy results in " + str(path))
    tax_files = list(path.glob(f"*contig2classification_named.txt"))
    print(str(len(tax_files)) + " files found. Combining tables...")
    dfs = []
    i = 0
    for file in tax_files:
        i += 1
        # Extract sample name
        sample = file.name.replace(".contig2classification_named.txt", "")
        if i % 10 == 0:
            print(str(i) + ": Parsing " + sample)
        df = pd.read_csv(file, sep = "\t")
        # Filter
        df_filt = filter_tax_ranks(df, tax_ranks)
        # Rename to match depth file
        df_filt = df_filt.rename(columns={"# contig": "contigName"})
        dfs.append(df_filt)
    combined = pd.concat(dfs, ignore_index=True)
    print("The combined table contains " + str(combined.shape[0]) + " contigs\n")
    return(combined)

def summarise_damage(combined, group):
    # Make sure damage is read as numeric
    combined["damage_model_pmax"] = pd.to_numeric(combined["damage_model_pmax"])
    # Remove NAs
    combined.dropna(inplace = True)
    # Unique bins retained
    combined.drop('contigName', axis=1, inplace=True)
    # Get grouping variables
    if group == "sample":
        var = ["sample"]
    elif group == "taxon":
        var = ["lineage"]
    elif group == "bin":
        var = ["bin"]
    elif group == "both":
        var = ["sample", "lineage"]
    print("Grouping based on ", str(var))
    # Sum abundances by sample and lineage and then pivot wider
    grouped = combined[var + ["damage_model_pmax"]].groupby(var).agg(
        min = ("damage_model_pmax", "min"),
        q1 = ("damage_model_pmax", lambda x: x.quantile(0.25)),
        mean = ("damage_model_pmax", "mean"),
        median = ("damage_model_pmax", "median"),
        q3 = ("damage_model_pmax", lambda x: x.quantile(0.75)),
        max = ("damage_model_pmax", "max")).reset_index()
    return(grouped)

def main():
    parser = argparse.ArgumentParser(description='Summarise pydamage of contigs by sample or taxon (latter requires CAT output)')
    parser.add_argument('--damage_dir', type=pathlib.Path, help='Path containing pydamage output')
    parser.add_argument('--damage_file', type=pathlib.Path, help='Path containing pydamage file (concatenated)')
    parser.add_argument('--taxonomy_dir', type=pathlib.Path, required = False, help='(Optional) Path containing taxonomic assignments (*.contig2classification_named.txt files) generated by CAT')
    parser.add_argument('--tax_ranks', type=str, default = "species", help='Taxonomic ranks to be used for the table (options are superkingdom, phylum, class, order, family, genus, species, and can be provided as a comma-separated list e.g. "species,genus")')
    parser.add_argument('--groupvar', type=str, default = "sample", help='Choose "sample", "taxon" (requires taxonomy info), "both", or "bin"')
    args = parser.parse_args()
    ranks = args.tax_ranks
    group = args.groupvar
    
    # Check if damage_dir or damage_file is provided
    if not(args.damage_dir) and not(args.damage_file):
        print("Error: Please provide either --damage_dir or --damage_file")
        exit(1)
    if args.damage_file and args.damage_dir:
        print("Error: Please provide only one of --damage_dir or --damage_file")
        exit(1)
    if args.damage_dir:
        # Parse depth files and decompress if necessary
        pydamage_combined = parse_damage_files(path = args.damage_dir)
    if args.damage_file:
        pydamage_combined = pd.read_csv(args.damage_file, sep = ",")
        pydamage_combined = pydamage_combined.rename(columns={"contig": "contigName"})
    
    # Check if taxdir is provided
    if args.taxonomy_dir:
        tax_dir = args.taxonomy_dir
        if group == "taxon":
            print("Grouping by taxon requires taxonomy info, which is provided\n")
    
    # Parse CAT files if taxonomy dir is provided
    if args.taxonomy_dir:
        # Parse taxonomic ranks
        print("Parse ranks list: " + ranks + "\n")
        ranks_ls = ranks.split(",")
        ranks_ls = [ x.strip() for x in ranks_ls ]
        tax_combined = parse_cat_files(tax_dir, tax_ranks = ranks_ls).astype(str)
        print("Combining taxonomy and damage tables")
        combined = pd.merge(pydamage_combined, tax_combined, on="contigName", how="inner")
        # Get sample name
        combined["sample"] = combined.contigName.str.replace(r'_final_contigs_k\d+_\d+', '', regex = True)
        # Combine the two
        summ_table = summarise_damage(combined, group)
    else:
        summ_table = summarise_damage(pydamage_combined, group)
    summ_table.to_csv("pydamage_summary.tsv", sep = "\t", index = False)

if __name__ == "__main__":
    main()